### ISSUE TITLE
Credentails Not Showing Up in DB & App Not Forwarding to Maintenance Screen

### ISSUE THREAD

**Issue by scoopyw** [ivan-sincek/phishing-mobile-app#5]
After a while waiting at the login screen it also says host unreachable.

If anyone can help me get this fixed it would be really appreciated.

**Comment by scoopyw** [comment]
For future people with the same problem: try putting your local ipv4 adress with port 80 in the api file.

**Comment by ivan-sincek** [comment]
Hi,

Thanks for the info.

I will not make any changes in the [/src/api/php/config.ini](https://github.com/ivan-sincek/phishing-mobile-app/blob/master/src/api/php/config.ini), but I will leave this issue for future references.
